// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

public interface edgeIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:edgeId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sourceId = 1;</code>
   * @return The sourceId.
   */
  String getSourceId();
  /**
   * <code>string sourceId = 1;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string destinationId = 2;</code>
   * @return The destinationId.
   */
  String getDestinationId();
  /**
   * <code>string destinationId = 2;</code>
   * @return The bytes for destinationId.
   */
  com.google.protobuf.ByteString
      getDestinationIdBytes();

  /**
   * <code>string label = 3;</code>
   * @return The label.
   */
  String getLabel();
  /**
   * <code>string label = 3;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
