// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

/**
 * Protobuf type {@code filterVerticesRequest}
 */
public final class filterVerticesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filterVerticesRequest)
    filterVerticesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use filterVerticesRequest.newBuilder() to construct.
  private filterVerticesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private filterVerticesRequest() {
    verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new filterVerticesRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private filterVerticesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              verticesIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            verticesIds_.add(s);
            break;
          }
          case 18: {
            vertexBinding.Builder subBuilder = null;
            if (vertexBinding_ != null) {
              subBuilder = vertexBinding_.toBuilder();
            }
            vertexBinding_ = input.readMessage(vertexBinding.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vertexBinding_);
              vertexBinding_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        verticesIds_ = verticesIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Traverser.internal_static_filterVerticesRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Traverser.internal_static_filterVerticesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            filterVerticesRequest.class, Builder.class);
  }

  public static final int VERTICESIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList verticesIds_;
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @return A list containing the verticesIds.
   */
  public com.google.protobuf.ProtocolStringList
      getVerticesIdsList() {
    return verticesIds_;
  }
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @return The count of verticesIds.
   */
  public int getVerticesIdsCount() {
    return verticesIds_.size();
  }
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @param index The index of the element to return.
   * @return The verticesIds at the given index.
   */
  public String getVerticesIds(int index) {
    return verticesIds_.get(index);
  }
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the verticesIds at the given index.
   */
  public com.google.protobuf.ByteString
      getVerticesIdsBytes(int index) {
    return verticesIds_.getByteString(index);
  }

  public static final int VERTEXBINDING_FIELD_NUMBER = 2;
  private vertexBinding vertexBinding_;
  /**
   * <code>.vertexBinding vertexBinding = 2;</code>
   * @return Whether the vertexBinding field is set.
   */
  @Override
  public boolean hasVertexBinding() {
    return vertexBinding_ != null;
  }
  /**
   * <code>.vertexBinding vertexBinding = 2;</code>
   * @return The vertexBinding.
   */
  @Override
  public vertexBinding getVertexBinding() {
    return vertexBinding_ == null ? vertexBinding.getDefaultInstance() : vertexBinding_;
  }
  /**
   * <code>.vertexBinding vertexBinding = 2;</code>
   */
  @Override
  public vertexBindingOrBuilder getVertexBindingOrBuilder() {
    return getVertexBinding();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < verticesIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, verticesIds_.getRaw(i));
    }
    if (vertexBinding_ != null) {
      output.writeMessage(2, getVertexBinding());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < verticesIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(verticesIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getVerticesIdsList().size();
    }
    if (vertexBinding_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getVertexBinding());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof filterVerticesRequest)) {
      return super.equals(obj);
    }
    filterVerticesRequest other = (filterVerticesRequest) obj;

    if (!getVerticesIdsList()
        .equals(other.getVerticesIdsList())) return false;
    if (hasVertexBinding() != other.hasVertexBinding()) return false;
    if (hasVertexBinding()) {
      if (!getVertexBinding()
          .equals(other.getVertexBinding())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVerticesIdsCount() > 0) {
      hash = (37 * hash) + VERTICESIDS_FIELD_NUMBER;
      hash = (53 * hash) + getVerticesIdsList().hashCode();
    }
    if (hasVertexBinding()) {
      hash = (37 * hash) + VERTEXBINDING_FIELD_NUMBER;
      hash = (53 * hash) + getVertexBinding().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static filterVerticesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filterVerticesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filterVerticesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filterVerticesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filterVerticesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filterVerticesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filterVerticesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static filterVerticesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static filterVerticesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static filterVerticesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static filterVerticesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static filterVerticesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(filterVerticesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filterVerticesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filterVerticesRequest)
      filterVerticesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Traverser.internal_static_filterVerticesRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Traverser.internal_static_filterVerticesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              filterVerticesRequest.class, Builder.class);
    }

    // Construct using com.server.graph_db.grpc.traverser.filterVerticesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (vertexBindingBuilder_ == null) {
        vertexBinding_ = null;
      } else {
        vertexBinding_ = null;
        vertexBindingBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Traverser.internal_static_filterVerticesRequest_descriptor;
    }

    @Override
    public filterVerticesRequest getDefaultInstanceForType() {
      return filterVerticesRequest.getDefaultInstance();
    }

    @Override
    public filterVerticesRequest build() {
      filterVerticesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public filterVerticesRequest buildPartial() {
      filterVerticesRequest result = new filterVerticesRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        verticesIds_ = verticesIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.verticesIds_ = verticesIds_;
      if (vertexBindingBuilder_ == null) {
        result.vertexBinding_ = vertexBinding_;
      } else {
        result.vertexBinding_ = vertexBindingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof filterVerticesRequest) {
        return mergeFrom((filterVerticesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(filterVerticesRequest other) {
      if (other == filterVerticesRequest.getDefaultInstance()) return this;
      if (!other.verticesIds_.isEmpty()) {
        if (verticesIds_.isEmpty()) {
          verticesIds_ = other.verticesIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureVerticesIdsIsMutable();
          verticesIds_.addAll(other.verticesIds_);
        }
        onChanged();
      }
      if (other.hasVertexBinding()) {
        mergeVertexBinding(other.getVertexBinding());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      filterVerticesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (filterVerticesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureVerticesIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        verticesIds_ = new com.google.protobuf.LazyStringArrayList(verticesIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @return A list containing the verticesIds.
     */
    public com.google.protobuf.ProtocolStringList
        getVerticesIdsList() {
      return verticesIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @return The count of verticesIds.
     */
    public int getVerticesIdsCount() {
      return verticesIds_.size();
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param index The index of the element to return.
     * @return The verticesIds at the given index.
     */
    public String getVerticesIds(int index) {
      return verticesIds_.get(index);
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the verticesIds at the given index.
     */
    public com.google.protobuf.ByteString
        getVerticesIdsBytes(int index) {
      return verticesIds_.getByteString(index);
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param index The index to set the value at.
     * @param value The verticesIds to set.
     * @return This builder for chaining.
     */
    public Builder setVerticesIds(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVerticesIdsIsMutable();
      verticesIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param value The verticesIds to add.
     * @return This builder for chaining.
     */
    public Builder addVerticesIds(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVerticesIdsIsMutable();
      verticesIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param values The verticesIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllVerticesIds(
        Iterable<String> values) {
      ensureVerticesIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, verticesIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerticesIds() {
      verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param value The bytes of the verticesIds to add.
     * @return This builder for chaining.
     */
    public Builder addVerticesIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureVerticesIdsIsMutable();
      verticesIds_.add(value);
      onChanged();
      return this;
    }

    private vertexBinding vertexBinding_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vertexBinding, vertexBinding.Builder, vertexBindingOrBuilder> vertexBindingBuilder_;
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     * @return Whether the vertexBinding field is set.
     */
    public boolean hasVertexBinding() {
      return vertexBindingBuilder_ != null || vertexBinding_ != null;
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     * @return The vertexBinding.
     */
    public vertexBinding getVertexBinding() {
      if (vertexBindingBuilder_ == null) {
        return vertexBinding_ == null ? vertexBinding.getDefaultInstance() : vertexBinding_;
      } else {
        return vertexBindingBuilder_.getMessage();
      }
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    public Builder setVertexBinding(vertexBinding value) {
      if (vertexBindingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vertexBinding_ = value;
        onChanged();
      } else {
        vertexBindingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    public Builder setVertexBinding(
        vertexBinding.Builder builderForValue) {
      if (vertexBindingBuilder_ == null) {
        vertexBinding_ = builderForValue.build();
        onChanged();
      } else {
        vertexBindingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    public Builder mergeVertexBinding(vertexBinding value) {
      if (vertexBindingBuilder_ == null) {
        if (vertexBinding_ != null) {
          vertexBinding_ =
            vertexBinding.newBuilder(vertexBinding_).mergeFrom(value).buildPartial();
        } else {
          vertexBinding_ = value;
        }
        onChanged();
      } else {
        vertexBindingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    public Builder clearVertexBinding() {
      if (vertexBindingBuilder_ == null) {
        vertexBinding_ = null;
        onChanged();
      } else {
        vertexBinding_ = null;
        vertexBindingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    public vertexBinding.Builder getVertexBindingBuilder() {
      
      onChanged();
      return getVertexBindingFieldBuilder().getBuilder();
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    public vertexBindingOrBuilder getVertexBindingOrBuilder() {
      if (vertexBindingBuilder_ != null) {
        return vertexBindingBuilder_.getMessageOrBuilder();
      } else {
        return vertexBinding_ == null ?
            vertexBinding.getDefaultInstance() : vertexBinding_;
      }
    }
    /**
     * <code>.vertexBinding vertexBinding = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vertexBinding, vertexBinding.Builder, vertexBindingOrBuilder>
        getVertexBindingFieldBuilder() {
      if (vertexBindingBuilder_ == null) {
        vertexBindingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vertexBinding, vertexBinding.Builder, vertexBindingOrBuilder>(
                getVertexBinding(),
                getParentForChildren(),
                isClean());
        vertexBinding_ = null;
      }
      return vertexBindingBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filterVerticesRequest)
  }

  // @@protoc_insertion_point(class_scope:filterVerticesRequest)
  private static final filterVerticesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new filterVerticesRequest();
  }

  public static filterVerticesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<filterVerticesRequest>
      PARSER = new com.google.protobuf.AbstractParser<filterVerticesRequest>() {
    @Override
    public filterVerticesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new filterVerticesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<filterVerticesRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<filterVerticesRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public filterVerticesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

