// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

/**
 * Protobuf type {@code vertexBinding}
 */
public final class vertexBinding extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vertexBinding)
    vertexBindingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use vertexBinding.newBuilder() to construct.
  private vertexBinding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private vertexBinding() {
    id_ = "";
    label_ = "";
    selectOperators_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new vertexBinding();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private vertexBinding(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            label_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              selectOperators_ = new java.util.ArrayList<selectOperator>();
              mutable_bitField0_ |= 0x00000001;
            }
            selectOperators_.add(
                input.readMessage(selectOperator.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        selectOperators_ = java.util.Collections.unmodifiableList(selectOperators_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Traverser.internal_static_vertexBinding_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Traverser.internal_static_vertexBinding_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vertexBinding.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private volatile Object label_;
  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  @Override
  public String getLabel() {
    Object ref = label_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    Object ref = label_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELECTOPERATORS_FIELD_NUMBER = 3;
  private java.util.List<selectOperator> selectOperators_;
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  @Override
  public java.util.List<selectOperator> getSelectOperatorsList() {
    return selectOperators_;
  }
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  @Override
  public java.util.List<? extends selectOperatorOrBuilder>
      getSelectOperatorsOrBuilderList() {
    return selectOperators_;
  }
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  @Override
  public int getSelectOperatorsCount() {
    return selectOperators_.size();
  }
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  @Override
  public selectOperator getSelectOperators(int index) {
    return selectOperators_.get(index);
  }
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  @Override
  public selectOperatorOrBuilder getSelectOperatorsOrBuilder(
      int index) {
    return selectOperators_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
    }
    for (int i = 0; i < selectOperators_.size(); i++) {
      output.writeMessage(3, selectOperators_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
    }
    for (int i = 0; i < selectOperators_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, selectOperators_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vertexBinding)) {
      return super.equals(obj);
    }
    vertexBinding other = (vertexBinding) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!getSelectOperatorsList()
        .equals(other.getSelectOperatorsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (getSelectOperatorsCount() > 0) {
      hash = (37 * hash) + SELECTOPERATORS_FIELD_NUMBER;
      hash = (53 * hash) + getSelectOperatorsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vertexBinding parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vertexBinding parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vertexBinding parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vertexBinding parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vertexBinding parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vertexBinding parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vertexBinding parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vertexBinding parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vertexBinding parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vertexBinding parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vertexBinding parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vertexBinding parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vertexBinding prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vertexBinding}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vertexBinding)
      vertexBindingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Traverser.internal_static_vertexBinding_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Traverser.internal_static_vertexBinding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vertexBinding.class, Builder.class);
    }

    // Construct using com.server.graph_db.grpc.traverser.vertexBinding.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSelectOperatorsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = "";

      label_ = "";

      if (selectOperatorsBuilder_ == null) {
        selectOperators_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        selectOperatorsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Traverser.internal_static_vertexBinding_descriptor;
    }

    @Override
    public vertexBinding getDefaultInstanceForType() {
      return vertexBinding.getDefaultInstance();
    }

    @Override
    public vertexBinding build() {
      vertexBinding result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public vertexBinding buildPartial() {
      vertexBinding result = new vertexBinding(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.label_ = label_;
      if (selectOperatorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          selectOperators_ = java.util.Collections.unmodifiableList(selectOperators_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.selectOperators_ = selectOperators_;
      } else {
        result.selectOperators_ = selectOperatorsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vertexBinding) {
        return mergeFrom((vertexBinding)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vertexBinding other) {
      if (other == vertexBinding.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      if (selectOperatorsBuilder_ == null) {
        if (!other.selectOperators_.isEmpty()) {
          if (selectOperators_.isEmpty()) {
            selectOperators_ = other.selectOperators_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSelectOperatorsIsMutable();
            selectOperators_.addAll(other.selectOperators_);
          }
          onChanged();
        }
      } else {
        if (!other.selectOperators_.isEmpty()) {
          if (selectOperatorsBuilder_.isEmpty()) {
            selectOperatorsBuilder_.dispose();
            selectOperatorsBuilder_ = null;
            selectOperators_ = other.selectOperators_;
            bitField0_ = (bitField0_ & ~0x00000001);
            selectOperatorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSelectOperatorsFieldBuilder() : null;
          } else {
            selectOperatorsBuilder_.addAllMessages(other.selectOperators_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vertexBinding parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vertexBinding) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private Object label_ = "";
    /**
     * <code>string label = 2;</code>
     * @return The label.
     */
    public String getLabel() {
      Object ref = label_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }

    private java.util.List<selectOperator> selectOperators_ =
      java.util.Collections.emptyList();
    private void ensureSelectOperatorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        selectOperators_ = new java.util.ArrayList<selectOperator>(selectOperators_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        selectOperator, selectOperator.Builder, selectOperatorOrBuilder> selectOperatorsBuilder_;

    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public java.util.List<selectOperator> getSelectOperatorsList() {
      if (selectOperatorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(selectOperators_);
      } else {
        return selectOperatorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public int getSelectOperatorsCount() {
      if (selectOperatorsBuilder_ == null) {
        return selectOperators_.size();
      } else {
        return selectOperatorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public selectOperator getSelectOperators(int index) {
      if (selectOperatorsBuilder_ == null) {
        return selectOperators_.get(index);
      } else {
        return selectOperatorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder setSelectOperators(
        int index, selectOperator value) {
      if (selectOperatorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSelectOperatorsIsMutable();
        selectOperators_.set(index, value);
        onChanged();
      } else {
        selectOperatorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder setSelectOperators(
        int index, selectOperator.Builder builderForValue) {
      if (selectOperatorsBuilder_ == null) {
        ensureSelectOperatorsIsMutable();
        selectOperators_.set(index, builderForValue.build());
        onChanged();
      } else {
        selectOperatorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder addSelectOperators(selectOperator value) {
      if (selectOperatorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSelectOperatorsIsMutable();
        selectOperators_.add(value);
        onChanged();
      } else {
        selectOperatorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder addSelectOperators(
        int index, selectOperator value) {
      if (selectOperatorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSelectOperatorsIsMutable();
        selectOperators_.add(index, value);
        onChanged();
      } else {
        selectOperatorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder addSelectOperators(
        selectOperator.Builder builderForValue) {
      if (selectOperatorsBuilder_ == null) {
        ensureSelectOperatorsIsMutable();
        selectOperators_.add(builderForValue.build());
        onChanged();
      } else {
        selectOperatorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder addSelectOperators(
        int index, selectOperator.Builder builderForValue) {
      if (selectOperatorsBuilder_ == null) {
        ensureSelectOperatorsIsMutable();
        selectOperators_.add(index, builderForValue.build());
        onChanged();
      } else {
        selectOperatorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder addAllSelectOperators(
        Iterable<? extends selectOperator> values) {
      if (selectOperatorsBuilder_ == null) {
        ensureSelectOperatorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, selectOperators_);
        onChanged();
      } else {
        selectOperatorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder clearSelectOperators() {
      if (selectOperatorsBuilder_ == null) {
        selectOperators_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        selectOperatorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public Builder removeSelectOperators(int index) {
      if (selectOperatorsBuilder_ == null) {
        ensureSelectOperatorsIsMutable();
        selectOperators_.remove(index);
        onChanged();
      } else {
        selectOperatorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public selectOperator.Builder getSelectOperatorsBuilder(
        int index) {
      return getSelectOperatorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public selectOperatorOrBuilder getSelectOperatorsOrBuilder(
        int index) {
      if (selectOperatorsBuilder_ == null) {
        return selectOperators_.get(index);  } else {
        return selectOperatorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public java.util.List<? extends selectOperatorOrBuilder>
         getSelectOperatorsOrBuilderList() {
      if (selectOperatorsBuilder_ != null) {
        return selectOperatorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(selectOperators_);
      }
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public selectOperator.Builder addSelectOperatorsBuilder() {
      return getSelectOperatorsFieldBuilder().addBuilder(
          selectOperator.getDefaultInstance());
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public selectOperator.Builder addSelectOperatorsBuilder(
        int index) {
      return getSelectOperatorsFieldBuilder().addBuilder(
          index, selectOperator.getDefaultInstance());
    }
    /**
     * <code>repeated .selectOperator selectOperators = 3;</code>
     */
    public java.util.List<selectOperator.Builder>
         getSelectOperatorsBuilderList() {
      return getSelectOperatorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        selectOperator, selectOperator.Builder, selectOperatorOrBuilder>
        getSelectOperatorsFieldBuilder() {
      if (selectOperatorsBuilder_ == null) {
        selectOperatorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            selectOperator, selectOperator.Builder, selectOperatorOrBuilder>(
                selectOperators_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        selectOperators_ = null;
      }
      return selectOperatorsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vertexBinding)
  }

  // @@protoc_insertion_point(class_scope:vertexBinding)
  private static final vertexBinding DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vertexBinding();
  }

  public static vertexBinding getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<vertexBinding>
      PARSER = new com.google.protobuf.AbstractParser<vertexBinding>() {
    @Override
    public vertexBinding parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new vertexBinding(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<vertexBinding> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<vertexBinding> getParserForType() {
    return PARSER;
  }

  @Override
  public vertexBinding getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

