// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

/**
 * Protobuf type {@code verticesIds}
 */
public final class verticesIds extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:verticesIds)
    verticesIdsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use verticesIds.newBuilder() to construct.
  private verticesIds(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private verticesIds() {
    verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new verticesIds();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private verticesIds(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              verticesIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            verticesIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        verticesIds_ = verticesIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Traverser.internal_static_verticesIds_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Traverser.internal_static_verticesIds_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            verticesIds.class, Builder.class);
  }

  public static final int VERTICESIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList verticesIds_;
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @return A list containing the verticesIds.
   */
  public com.google.protobuf.ProtocolStringList
      getVerticesIdsList() {
    return verticesIds_;
  }
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @return The count of verticesIds.
   */
  public int getVerticesIdsCount() {
    return verticesIds_.size();
  }
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @param index The index of the element to return.
   * @return The verticesIds at the given index.
   */
  public String getVerticesIds(int index) {
    return verticesIds_.get(index);
  }
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the verticesIds at the given index.
   */
  public com.google.protobuf.ByteString
      getVerticesIdsBytes(int index) {
    return verticesIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < verticesIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, verticesIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < verticesIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(verticesIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getVerticesIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof verticesIds)) {
      return super.equals(obj);
    }
    verticesIds other = (verticesIds) obj;

    if (!getVerticesIdsList()
        .equals(other.getVerticesIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVerticesIdsCount() > 0) {
      hash = (37 * hash) + VERTICESIDS_FIELD_NUMBER;
      hash = (53 * hash) + getVerticesIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static verticesIds parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static verticesIds parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static verticesIds parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static verticesIds parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static verticesIds parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static verticesIds parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static verticesIds parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static verticesIds parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static verticesIds parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static verticesIds parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static verticesIds parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static verticesIds parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(verticesIds prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code verticesIds}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:verticesIds)
      verticesIdsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Traverser.internal_static_verticesIds_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Traverser.internal_static_verticesIds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              verticesIds.class, Builder.class);
    }

    // Construct using com.server.graph_db.grpc.traverser.verticesIds.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Traverser.internal_static_verticesIds_descriptor;
    }

    @Override
    public verticesIds getDefaultInstanceForType() {
      return verticesIds.getDefaultInstance();
    }

    @Override
    public verticesIds build() {
      verticesIds result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public verticesIds buildPartial() {
      verticesIds result = new verticesIds(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        verticesIds_ = verticesIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.verticesIds_ = verticesIds_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof verticesIds) {
        return mergeFrom((verticesIds)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(verticesIds other) {
      if (other == verticesIds.getDefaultInstance()) return this;
      if (!other.verticesIds_.isEmpty()) {
        if (verticesIds_.isEmpty()) {
          verticesIds_ = other.verticesIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureVerticesIdsIsMutable();
          verticesIds_.addAll(other.verticesIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      verticesIds parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (verticesIds) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureVerticesIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        verticesIds_ = new com.google.protobuf.LazyStringArrayList(verticesIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @return A list containing the verticesIds.
     */
    public com.google.protobuf.ProtocolStringList
        getVerticesIdsList() {
      return verticesIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @return The count of verticesIds.
     */
    public int getVerticesIdsCount() {
      return verticesIds_.size();
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param index The index of the element to return.
     * @return The verticesIds at the given index.
     */
    public String getVerticesIds(int index) {
      return verticesIds_.get(index);
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the verticesIds at the given index.
     */
    public com.google.protobuf.ByteString
        getVerticesIdsBytes(int index) {
      return verticesIds_.getByteString(index);
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param index The index to set the value at.
     * @param value The verticesIds to set.
     * @return This builder for chaining.
     */
    public Builder setVerticesIds(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVerticesIdsIsMutable();
      verticesIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param value The verticesIds to add.
     * @return This builder for chaining.
     */
    public Builder addVerticesIds(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVerticesIdsIsMutable();
      verticesIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param values The verticesIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllVerticesIds(
        Iterable<String> values) {
      ensureVerticesIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, verticesIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerticesIds() {
      verticesIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string verticesIds = 1;</code>
     * @param value The bytes of the verticesIds to add.
     * @return This builder for chaining.
     */
    public Builder addVerticesIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureVerticesIdsIsMutable();
      verticesIds_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:verticesIds)
  }

  // @@protoc_insertion_point(class_scope:verticesIds)
  private static final verticesIds DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new verticesIds();
  }

  public static verticesIds getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<verticesIds>
      PARSER = new com.google.protobuf.AbstractParser<verticesIds>() {
    @Override
    public verticesIds parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new verticesIds(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<verticesIds> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<verticesIds> getParserForType() {
    return PARSER;
  }

  @Override
  public verticesIds getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

