// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface createEdgeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:createEdgeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sourceVertexId = 1;</code>
   * @return The sourceVertexId.
   */
  String getSourceVertexId();
  /**
   * <code>string sourceVertexId = 1;</code>
   * @return The bytes for sourceVertexId.
   */
  com.google.protobuf.ByteString
      getSourceVertexIdBytes();

  /**
   * <code>string destinationVertexId = 2;</code>
   * @return The destinationVertexId.
   */
  String getDestinationVertexId();
  /**
   * <code>string destinationVertexId = 2;</code>
   * @return The bytes for destinationVertexId.
   */
  com.google.protobuf.ByteString
      getDestinationVertexIdBytes();

  /**
   * <code>string label = 3;</code>
   * @return The label.
   */
  String getLabel();
  /**
   * <code>string label = 3;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  boolean containsProperties(
      String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getProperties();
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  java.util.Map<String, String>
  getPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */

  String getPropertiesOrDefault(
      String key,
      String defaultValue);
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */

  String getPropertiesOrThrow(
      String key);

  /**
   * <pre>
   *boolean variable
   * </pre>
   *
   * <code>bool isOutGoing = 5;</code>
   * @return The isOutGoing.
   */
  boolean getIsOutGoing();
}
