// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

/**
 * Protobuf type {@code deleteEdgeRequest}
 */
public final class deleteEdgeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deleteEdgeRequest)
    deleteEdgeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use deleteEdgeRequest.newBuilder() to construct.
  private deleteEdgeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private deleteEdgeRequest() {
    sourceVertexId_ = "";
    destinationVertexId_ = "";
    label_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new deleteEdgeRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private deleteEdgeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            sourceVertexId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            destinationVertexId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            label_ = s;
            break;
          }
          case 32: {

            isOutGoing_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Vertex.internal_static_deleteEdgeRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Vertex.internal_static_deleteEdgeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            deleteEdgeRequest.class, Builder.class);
  }

  public static final int SOURCEVERTEXID_FIELD_NUMBER = 1;
  private volatile Object sourceVertexId_;
  /**
   * <code>string sourceVertexId = 1;</code>
   * @return The sourceVertexId.
   */
  @Override
  public String getSourceVertexId() {
    Object ref = sourceVertexId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sourceVertexId_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceVertexId = 1;</code>
   * @return The bytes for sourceVertexId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSourceVertexIdBytes() {
    Object ref = sourceVertexId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sourceVertexId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONVERTEXID_FIELD_NUMBER = 2;
  private volatile Object destinationVertexId_;
  /**
   * <code>string destinationVertexId = 2;</code>
   * @return The destinationVertexId.
   */
  @Override
  public String getDestinationVertexId() {
    Object ref = destinationVertexId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      destinationVertexId_ = s;
      return s;
    }
  }
  /**
   * <code>string destinationVertexId = 2;</code>
   * @return The bytes for destinationVertexId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDestinationVertexIdBytes() {
    Object ref = destinationVertexId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      destinationVertexId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 3;
  private volatile Object label_;
  /**
   * <code>string label = 3;</code>
   * @return The label.
   */
  @Override
  public String getLabel() {
    Object ref = label_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 3;</code>
   * @return The bytes for label.
   */
  @Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    Object ref = label_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOUTGOING_FIELD_NUMBER = 4;
  private boolean isOutGoing_;
  /**
   * <code>bool isOutGoing = 4;</code>
   * @return The isOutGoing.
   */
  @Override
  public boolean getIsOutGoing() {
    return isOutGoing_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSourceVertexIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceVertexId_);
    }
    if (!getDestinationVertexIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destinationVertexId_);
    }
    if (!getLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, label_);
    }
    if (isOutGoing_ != false) {
      output.writeBool(4, isOutGoing_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSourceVertexIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceVertexId_);
    }
    if (!getDestinationVertexIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destinationVertexId_);
    }
    if (!getLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, label_);
    }
    if (isOutGoing_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isOutGoing_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof deleteEdgeRequest)) {
      return super.equals(obj);
    }
    deleteEdgeRequest other = (deleteEdgeRequest) obj;

    if (!getSourceVertexId()
        .equals(other.getSourceVertexId())) return false;
    if (!getDestinationVertexId()
        .equals(other.getDestinationVertexId())) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (getIsOutGoing()
        != other.getIsOutGoing()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCEVERTEXID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceVertexId().hashCode();
    hash = (37 * hash) + DESTINATIONVERTEXID_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationVertexId().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    hash = (37 * hash) + ISOUTGOING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOutGoing());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static deleteEdgeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static deleteEdgeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static deleteEdgeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static deleteEdgeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static deleteEdgeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static deleteEdgeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static deleteEdgeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static deleteEdgeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static deleteEdgeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static deleteEdgeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static deleteEdgeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static deleteEdgeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(deleteEdgeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code deleteEdgeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deleteEdgeRequest)
      deleteEdgeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Vertex.internal_static_deleteEdgeRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Vertex.internal_static_deleteEdgeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              deleteEdgeRequest.class, Builder.class);
    }

    // Construct using com.server.graph_db.grpc.vertex.deleteEdgeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      sourceVertexId_ = "";

      destinationVertexId_ = "";

      label_ = "";

      isOutGoing_ = false;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Vertex.internal_static_deleteEdgeRequest_descriptor;
    }

    @Override
    public deleteEdgeRequest getDefaultInstanceForType() {
      return deleteEdgeRequest.getDefaultInstance();
    }

    @Override
    public deleteEdgeRequest build() {
      deleteEdgeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public deleteEdgeRequest buildPartial() {
      deleteEdgeRequest result = new deleteEdgeRequest(this);
      result.sourceVertexId_ = sourceVertexId_;
      result.destinationVertexId_ = destinationVertexId_;
      result.label_ = label_;
      result.isOutGoing_ = isOutGoing_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof deleteEdgeRequest) {
        return mergeFrom((deleteEdgeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(deleteEdgeRequest other) {
      if (other == deleteEdgeRequest.getDefaultInstance()) return this;
      if (!other.getSourceVertexId().isEmpty()) {
        sourceVertexId_ = other.sourceVertexId_;
        onChanged();
      }
      if (!other.getDestinationVertexId().isEmpty()) {
        destinationVertexId_ = other.destinationVertexId_;
        onChanged();
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      if (other.getIsOutGoing() != false) {
        setIsOutGoing(other.getIsOutGoing());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      deleteEdgeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (deleteEdgeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object sourceVertexId_ = "";
    /**
     * <code>string sourceVertexId = 1;</code>
     * @return The sourceVertexId.
     */
    public String getSourceVertexId() {
      Object ref = sourceVertexId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sourceVertexId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sourceVertexId = 1;</code>
     * @return The bytes for sourceVertexId.
     */
    public com.google.protobuf.ByteString
        getSourceVertexIdBytes() {
      Object ref = sourceVertexId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sourceVertexId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceVertexId = 1;</code>
     * @param value The sourceVertexId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceVertexId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceVertexId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceVertexId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceVertexId() {
      
      sourceVertexId_ = getDefaultInstance().getSourceVertexId();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceVertexId = 1;</code>
     * @param value The bytes for sourceVertexId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceVertexIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceVertexId_ = value;
      onChanged();
      return this;
    }

    private Object destinationVertexId_ = "";
    /**
     * <code>string destinationVertexId = 2;</code>
     * @return The destinationVertexId.
     */
    public String getDestinationVertexId() {
      Object ref = destinationVertexId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destinationVertexId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string destinationVertexId = 2;</code>
     * @return The bytes for destinationVertexId.
     */
    public com.google.protobuf.ByteString
        getDestinationVertexIdBytes() {
      Object ref = destinationVertexId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destinationVertexId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destinationVertexId = 2;</code>
     * @param value The destinationVertexId to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationVertexId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationVertexId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destinationVertexId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationVertexId() {
      
      destinationVertexId_ = getDefaultInstance().getDestinationVertexId();
      onChanged();
      return this;
    }
    /**
     * <code>string destinationVertexId = 2;</code>
     * @param value The bytes for destinationVertexId to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationVertexIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationVertexId_ = value;
      onChanged();
      return this;
    }

    private Object label_ = "";
    /**
     * <code>string label = 3;</code>
     * @return The label.
     */
    public String getLabel() {
      Object ref = label_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string label = 3;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 3;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string label = 3;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }

    private boolean isOutGoing_ ;
    /**
     * <code>bool isOutGoing = 4;</code>
     * @return The isOutGoing.
     */
    @Override
    public boolean getIsOutGoing() {
      return isOutGoing_;
    }
    /**
     * <code>bool isOutGoing = 4;</code>
     * @param value The isOutGoing to set.
     * @return This builder for chaining.
     */
    public Builder setIsOutGoing(boolean value) {
      
      isOutGoing_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isOutGoing = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOutGoing() {
      
      isOutGoing_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deleteEdgeRequest)
  }

  // @@protoc_insertion_point(class_scope:deleteEdgeRequest)
  private static final deleteEdgeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new deleteEdgeRequest();
  }

  public static deleteEdgeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<deleteEdgeRequest>
      PARSER = new com.google.protobuf.AbstractParser<deleteEdgeRequest>() {
    @Override
    public deleteEdgeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new deleteEdgeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<deleteEdgeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<deleteEdgeRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public deleteEdgeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

